name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v1
    - name: Log in to Docker Hub
      if: ${{ github.ref_type == 'tag' }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
    - run: | 
        docker build --tag phildaniels/azurefunctionsdiscordbot:v1.0.0 .
        docker push phildaniels/azurefunctionsdiscordbot:v1.0.0
