name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.7.0
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ 
          github.event.base_ref =='refs/heads/main' && 
          github.ref_type == 'tag' && 
          !startsWith(github.ref, 'refs/tags/v0.') 
          }}
        tags: phildaniels/azurefunctionsdiscordbot:v1.0.0
